version 2 :

models:
- name: stg_cc_sales
  columns:
    - name: date_date
      tests:
      - not_null
    - name: product_id
      tests:
      - not_null
    - name : qty
      tests:
      - not_null

- name: stg_cc_stock
  columns:
    - name: product_id
      tests:
        - not_null
        - unique
    - name: product_name
      tests:
        - not_null
        

      
      